set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'tomasr/molokai'
    Plugin 'kien/ctrlp.vim'
    Plugin 'scrooloose/nerdtree'
    Plugin 'scrooloose/syntastic'
    Plugin 'Raimondi/delimitMate'
    Plugin 'fatih/vim-go'
    Plugin 'valloric/youcompleteme'
    Plugin 'mileszs/ack.vim'
    Plugin 'nightsense/seabird'
call vundle#end()
filetype plugin indent on

syntax on


" COMMON SETTINGS
let mapleader=","
set backspace=2


" WHITESPACING
set autoindent
set tabstop=4          " number of visual spaces per TAB
set softtabstop=4      " number of spaces in tab when editing
set shiftwidth=4
set expandtab          " tabs are spaces


" UI CONFIG
set number             " show line numbers
"set cursorline         " highlight current line 
filetype indent on     " load filetype-specific indent files
set wildmenu           " autocomplete visual-box for command menu
set lazyredraw         " only redraw when needed
set showmatch          " highlight matching [{()}]


" SEARCHING
set incsearch          " search while typing
set hlsearch           " highlight matches
" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>
noremap <Leader>a :Ack <cword><cr>

" MOVEMENT
" move to beginning/end of line
nnoremap B ^
nnoremap E $
" $/^ doesn't do anything
nnoremap $ <nop>
nnoremap ^ <nop>


" CUSTOM KEYBINDINGS
map <C-n> :NERDTreeToggle<CR>
map <leader>T :NERDTreeFind<CR>
map <leader>r :nohlsearch<CR>
vmap <C-c> :w !pbcopy<CR><CR>


" YOU COMPLETE ME - SETTINGS
" If you prefer the Omni-Completion tip window to close when a selection is
" made, these lines close it on movement in insert mode or when leaving
" insert mode
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif


" GOLANG
let g:go_fmt_command = "goimports"
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:go_list_type = "quickfix"
au FileType go nmap <leader>b <Plug>(go-build)
"au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)
au FileType go nmap <leader>i <Plug>(go-info)

" JAVASCRIPT
au FileType javascript set tabstop=2          " number of visual spaces per TAB
au FileType javascript set softtabstop=2      " number of spaces in tab when editing
au FileType javascript set shiftwidth=2

if filereadable(expand("~/.vim/bundle/molokai/colors/molokai.vim"))
    colorscheme molokai
endif

